# -*- coding: utf-8 -*-
"""projek anemia tugas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjFQaq0E8TVmP5oGU-E04oH8xcRGnbR1

1. Import Library
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""2. Hubungkan Google Drive"""

drive.mount('/content/drive')

"""3. Membaca Dataset dari Google Drive"""

import os

df = pd.read_csv('/content/drive/MyDrive/Big Data/DATASET/anemia.csv')

df.head()

"""4. Informasi Dataset"""

df.info()

"""5. Melihat Ukuran Dataset"""

print("Jumlah Baris dan Kolom :", df.shape)

"""6. Mengecek Missing Value"""

print(df.isnull().sum())

"""7. Mengecek Data Duplikat"""

print("Jumlah Data Duplikat :", df.duplicated().sum())

"""8. Statistik Deskriptif"""

df.describe()

"""9. Menampilkan Tipe Data"""

print(df.dtypes)

"""10. Histogram Semua Variabel"""

df.hist(figsize=(12,10))

plt.suptitle('Histogram Semua Variabel')

plt.show()

"""11. Heatmap Korelasi"""

plt.figure(figsize=(10,8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Heatmap Korelasi Semua Variabel')

plt.show()

"""12. Menampilkan Korelasi terhadap Hemoglobin"""

print(df.corr(numeric_only=True)['Hemoglobin'].sort_values(ascending=False))

"""13. Scatter Plot"""

plt.figure(figsize=(6,5))

plt.scatter(df['MCH'], df['Hemoglobin'])

plt.xlabel('MCH')
plt.ylabel('Hemoglobin')

plt.title('Scatter Plot MCH terhadap Hemoglobin')

plt.show()

"""14. Regplot Regresi Linier"""

plt.figure(figsize=(6,5))

sns.regplot(
    x='MCH',
    y='Hemoglobin',
    data=df
)

plt.title('Regresi Linier MCH terhadap Hemoglobin')

plt.show()

"""15. Menentukan Variabel X dan y"""

X = df[['MCH', 'MCHC', 'MCV']]
y = df['Hemoglobin']

"""16. Split Data Training dan Testing"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Output Data Training dan testing"""

print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

"""17. Membuat Model Regresi Linier"""

model = LinearRegression()

model.fit(X_train, y_train)

"""18. Menampilkan Koefisien Regresi"""

print("Koefisien Regresi :")
print(model.coef_)

print("\nIntercept :")
print(model.intercept_)

"""19. Melakukan Prediksi"""

y_pred = model.predict(X_test)

print(y_pred[:10])

"""20. Evaluasi Model Regresi Linier"""

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)

print("MSE :", mse)

print("RMSE :", rmse)

print("R2 Score :", r2)

"""21. Membuat Tabel Actual dan Prediction"""

hasil = pd.DataFrame({
    'Actual': y_test,
    'Prediction': y_pred
})

hasil.head(10)

plt.figure(figsize=(6,5))

plt.scatter(y_test, y_pred)

plt.xlabel('Actual')
plt.ylabel('Prediction')

plt.title('Actual vs Prediction')

plt.show()

"""22.Line Graph"""

plt.figure(figsize=(10,6))

plt.plot(y_test.values, label='Actual Hemoglobin', color='blue')
plt.plot(y_pred, label='Predicted Hemoglobin', color='red', linestyle='--')

plt.title('Actual vs. Predicted Hemoglobin Values (Line Graph)')
plt.xlabel('Sample Index')
plt.ylabel('Hemoglobin Level')
plt.legend()
plt.grid(True)
plt.show()

"""## 23. Mencoba Model Lain (e.g., Random Forest Regressor)"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest Regressor Model Trained Successfully.")

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest Regressor Model Trained Successfully.")

"""## 24. Melakukan Prediksi dengan Random Forest"""

y_pred_rf = rf_model.predict(X_test)

print(y_pred_rf[:10])

"""## 25. Evaluasi Model Random Forest Regressor"""

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regressor Evaluation:")
print(f"MAE : {mae_rf}")
print(f"MSE : {mse_rf}")
print(f"RMSE : {rmse_rf}")
print(f"R2 Score : {r2_rf}")

"""## 26. Prediksi Interaktif dengan Model Random Forest

Di bagian ini, Anda dapat mencoba memprediksi kadar Hemoglobin secara interaktif menggunakan model Random Forest yang telah dilatih. Sesuaikan nilai MCH, MCHC, dan MCV di bawah untuk melihat bagaimana kadar Hemoglobin yang diprediksi berubah.
"""

from ipywidgets import interact, FloatSlider
from IPython.display import display
import pandas as pd # Import pandas
from google.colab import drive # Import drive

# Ensure Google Drive is mounted for this cell's execution
drive.mount('/content/drive', force_remount=True)

# Re-load df to ensure it's available in this cell's scope
df = pd.read_csv('/content/drive/MyDrive/Big Data/DATASET/anemia.csv')

# Pre-calculate mean values for the sliders
mch_mean_val = df['MCH'].mean()
mchc_mean_val = df['MCHC'].mean()
mcv_mean_val = df['MCV'].mean()

def predict_interactive(mch, mchc, mcv):
    # Create a DataFrame from the input values
    input_data = pd.DataFrame([[mch, mchc, mcv]], columns=['MCH', 'MCHC', 'MCV'])

    # Make a prediction using the Random Forest model
    # This assumes rf_model is defined and trained from previous cells.
    predicted_hemoglobin = rf_model.predict(input_data)[0]

    print(f"Prediksi Kadar Hemoglobin: {predicted_hemoglobin:.3f}")

print("Atur slider di bawah untuk mendapatkan prediksi Hemoglobin:")

# Define the sliders with ranges based on dataset statistics
interact(
    predict_interactive,
    mch=FloatSlider(min=14.8, max=30.8, step=0.1, value=mch_mean_val, description='MCH:'),
    mchc=FloatSlider(min=26.5, max=34.1, step=0.1, value=mchc_mean_val, description='MCHC:'),
    mcv=FloatSlider(min=68.3, max=102.8, step=0.1, value=mcv_mean_val, description='MCV:')
);

import joblib

joblib.dump(model, "model.pkl")

from google.colab import files
files.download("model.pkl")